export const BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL;
export const BRAND_NAME = process.env.NEXT_PUBLIC_BRAND_NAME;
export const STEADFAST_BASE_URL =
  process.env.NEXT_PUBLIC_STEADFAST_COURIER_API_BASE_URL;
export const STEADFAST_API_KEY =
  process.env.NEXT_PUBLIC_STEADFAST_COURIER_API_KEY;
export const STEADFAST_SECRET_KEY =
  process.env.NEXT_PUBLIC_STEADFAST_COURIER_SECRET_KEY;
