const AuthRouter = require("./routes/auth.route.js");
const BannerRouter = require("./routes/banner.route.js");
const AboutUsRouter = require("./routes/aboutUs.route.js");
const BrandRouter = require("./routes/brand.route.js");
const CategoryRouter = require("./routes/category.route.js");
const ContactRouter = require("./routes/contactInfo.route.js");
const CouponRouter = require("./routes/coupon.route.js");
const InventoryRouter = require("./routes/inventory.route.js");
const OrderRouter = require("./routes/order.route.js");
const PolicyRouter = require("./routes/policy.route.js");
const ProductRouter = require("./routes/product.route.js");
const SubCategoryRouter = require("./routes/subCategory.route.js");
const ChildCategoryRouter = require("./routes/childCategory.route.js");
const SubChildCategoryRouter = require("./routes/subChildCategory.route.js");
const NewsletterRouter = require("./routes/newsletter.route.js");
const PaymentServiceConfigRouter = require("./routes/paymentServiceConfig.route.js");
const ShippingMethodRouter = require("./routes/shippingMethod.route.js");
const RoleRouter = require("./routes/role.route.js");
const ReportRoute = require("./routes/report.route.js");
const UserRouter = require("./routes/user.route.js");
const CartRouter = require("./routes/cart.route.js");
const WishlistRouter = require("./routes/wishlist.js");
const ProductReviewRouter = require("./routes/productReview.route.js");
const WarehouseRoute = require("./routes/warehouse.route.js");
const WarehouseTransferRoute = require("./routes/warehouseTransfer.route.js");
const OrderBulkRoute = require("./routes/order.bulk.route.js");
const BlogTagRoute = require("./routes/blogTag.route.js");
const BlogRoute = require("./routes/blog.route.js");

const { Router } = require("express");
const CampaignRoute = require("./routes/campaign.route.js");
const rootRouter = Router();
rootRouter.use("/product", ProductRouter);
rootRouter.use("/auth", AuthRouter);
rootRouter.use("/banners", BannerRouter);
rootRouter.use("/about-us", AboutUsRouter);
rootRouter.use("/brand", BrandRouter);
rootRouter.use("/category", CategoryRouter);
rootRouter.use("/contact-info", ContactRouter);
rootRouter.use("/coupon", CouponRouter);
rootRouter.use("/inventory", InventoryRouter);
rootRouter.use("/order", OrderRouter);
rootRouter.use("/policy", PolicyRouter);
rootRouter.use("/newsletter", NewsletterRouter);
rootRouter.use("/sub-category", SubCategoryRouter);
rootRouter.use("/child-category", ChildCategoryRouter);
rootRouter.use("/sub-child-category", SubChildCategoryRouter);
rootRouter.use("/shipping-method", PaymentServiceConfigRouter);
rootRouter.use("/payment-service-config", ShippingMethodRouter);
rootRouter.use("/role", RoleRouter);
rootRouter.use("/shipping-method", ShippingMethodRouter);
rootRouter.use("/payment-service-config", PaymentServiceConfigRouter);
rootRouter.use("/user", UserRouter);
rootRouter.use("/cart", CartRouter);
rootRouter.use("/newsletter", CartRouter);
rootRouter.use("/product-review", ProductReviewRouter);
rootRouter.use("/wish-list", WishlistRouter);
rootRouter.use("/report", ReportRoute);
rootRouter.use("/warehouse", WarehouseRoute);
rootRouter.use("/warehouse-transfer", WarehouseTransferRoute);
rootRouter.use("/order-bulk", OrderBulkRoute);
rootRouter.use("/campaign", CampaignRoute);
rootRouter.use("/blog", BlogRoute);
rootRouter.use("/blog-tag", BlogTagRoute);

module.exports = rootRouter;
